version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: extended-umbrella-lnswitchboard_app_1
      APP_PORT: 22121
      PROXY_AUTH_WHITELIST: "/.well-known/*"
  app:
    image: ghcr.io/ryleastark/lnswitchboard:0.1.34@sha256:d811a9be355e9d9293a9af4a95b15369c56752f815396e94c01e1a0eb1810c36
    user: "1000:1000"
    restart: on-failure
    environment:
      SERVICE_PORT: 22121
      LND_HOST: "$APP_LIGHTNING_NODE_IP"
      LND_GRPC_PORT: "$APP_LIGHTNING_NODE_GRPC_PORT"
      DATA_STORE_PATH: "/app/secrets/lnswitchboard.db"
      LND_TLS_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/invoice.macaroon"
      LND_READONLY_MACAROON_PATH: "/lnd/readonly.macaroon"
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/invoice.macaroon:/lnd/invoice.macaroon:ro
      - ${APP_LIGHTNING_NODE_DATA_DIR}/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/readonly.macaroon:/lnd/readonly.macaroon:ro
      - ${APP_LIGHTNING_NODE_DATA_DIR}/tls.cert:/lnd/tls.cert:ro
      - ${APP_DATA_DIR}/data/secrets:/app/secrets:rw